# Generated by Django 5.2.6 on 2025-09-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(height_field=500, null=True, upload_to='', width_field=500),
        ),
    ]
