# Generated by Django 5.2.6 on 2025-10-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_image_height_product_image_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(height_field='image_height', null=True, upload_to='images', width_field='image_width'),
        ),
    ]
